#sasFilePath: automation_sample/multi_join_expression.sas
#conversionTime: 01/03/2025 07:55:31
#linesInFile: 291 #linesOfCode: 259 #linesOfPython: 257
#complexity: 2 #processedBlocks: 2 #passedBlocks: 2
#failedBlocks: 0 #totalErrors: 0


expression = [
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.PACKNAME_ID), 'A') AS PACKNAME_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.PRODUCTNAME_ID), 'A') AS PRODUCTNAME_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.STRENGTHRATE_ID), 'A') AS STRENGTHRATE_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.MOLECULENAME_ID), 'A') AS MOLECULENAME_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.NFC123CODE_ID), 'A') AS NFC123CODE_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.MANUFACTURERNAME_ID), 'A') AS MANUFACTURERNAME_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.INTERNATIONALPRODUCTNAME_ID), 'A') AS INTERNATIONALPRODUCTNAME_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.CORPORATIONNAME_ID), 'A') AS CORPORATIONNAME_ID_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.PRODUCTATC3_CD), 'A') AS PRODUCTATC3_CD_JOIN1""",
"""COALESCE(TRIM(ODS_TRANS_INMARKETSALES.PRODUCTATC4_CD), 'A') AS PRODUCTATC4_CD_JOIN1"""
]

informatica_insertinto(
    source = (tbl("SASWORK.ODS_TRANS_INMARKETSALES"), alias("ODS_TRANS_INMARKETSALES")),
    truncate = True,
    expression = expression,
    expressionname = tbl("ODS_TRANS_INMARKETSALES_JOIN1")

)



expression = [
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCTPACK_NM), 'A') AS PRODUCTPACK_NM_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCT_NM), 'A') AS PRODUCT_NM_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCTSTRENGTH_RT), 'A') AS PRODUCTSTRENGTH_RT_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCTMOLECULE_NM), 'A') AS PRODUCTMOLECULE_NM_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.NFC123_CD), 'A') AS NFC123_CD_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCTMANUFACTURER_NM), 'A') AS PRODUCTMANUFACTURER_NM_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.INTERNATIONALPRODUCT_NM), 'A') AS INTERNATIONALPRODUCT_NM_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCTCORPORATION_NM), 'A') AS PRODUCTCORPORATION_NM_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCTATC3_CD), 'A') AS PRODUCTATC3_CD_JOIN2""",
"""COALESCE(TRIM(EDW_CML_DIM_PRODUCT.PRODUCTATC4_CD), 'A') AS PRODUCTATC4_CD_JOIN2"""
]

informatica_insertinto(
    source = (tbl("SASWORK.EDW_CML_DIM_PRODUCT"), alias("EDW_CML_DIM_PRODUCT")),
    truncate = True,
    expression = expression,
    expressionname = tbl("EDW_CML_DIM_PRODUCT_JOIN2")

)



informatica_simple_join(
      left = (tbl("ODS_TRANS_INMARKETSALES_JOIN1"), alias("ODS_TRANS_INMARKETSALES")),
      right = (tbl("EDW_CML_DIM_PRODUCT_JOIN2"), alias("EDW_CML_DIM_PRODUCT")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART1"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.PACKNAME_ID_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCTPACK_NM_JOIN2 AND
 ODS_TRANS_INMARKETSALES.PRODUCTNAME_ID_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCT_NM_JOIN2 AND
 ODS_TRANS_INMARKETSALES.STRENGTHRATE_ID_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCTSTRENGTH_RT_JOIN2 AND
 ODS_TRANS_INMARKETSALES.MOLECULENAME_ID_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCTMOLECULE_NM_JOIN2 AND
 ODS_TRANS_INMARKETSALES.NFC123CODE_ID_JOIN1=EDW_CML_DIM_PRODUCT.NFC123_CD_JOIN2 AND
 ODS_TRANS_INMARKETSALES.MANUFACTURERNAME_ID_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCTMANUFACTURER_NM_JOIN2 AND
 ODS_TRANS_INMARKETSALES.INTERNATIONALPRODUCTNAME_ID_JOIN1=EDW_CML_DIM_PRODUCT.INTERNATIONALPRODUCT_NM_JOIN2 AND
 ODS_TRANS_INMARKETSALES.CORPORATIONNAME_ID_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCTCORPORATION_NM_JOIN2 AND
 ODS_TRANS_INMARKETSALES.PRODUCTATC3_CD_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCTATC3_CD_JOIN2 AND
 ODS_TRANS_INMARKETSALES.PRODUCTATC4_CD_JOIN1=EDW_CML_DIM_PRODUCT.PRODUCTATC4_CD_JOIN2
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART1"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART1")),
      right = (tbl("EDW_CML_DIM_COUNTRY"), alias("EDW_CML_DIM_COUNTRY")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART2"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.FINALDESTINATIONCOUNTRYCODE_ID=EDW_CML_DIM_COUNTRY.COUNTRYCODE_ID
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART2"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART2")),
      right = (tbl("EDW_CML_DIM_MATERIAL"), alias("EDW_CML_DIM_MATERIAL")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART3"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.MATERIALCODE_ID=EDW_CML_DIM_MATERIAL.MATERIALCODE_ID
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART3"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART3")),
      right = (tbl("ODS_TRANS_INMARKETSALES"), alias("ODS_TRANS_INMARKETSALES")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART4"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.PRODUCTFAMILYCODE_ID=EDW_DIM_PRODUCTFAMILY.PRODUCTFAMILYCODE_ID
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART4"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART4")),
      right = (tbl("EDW_CML_DIM_CURRENCY"), alias("EDW_CML_DIM_CURRENCY")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART5"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.LOCALCURRENCYCODE_ID=EDW_CML_DIM_CURRENCY.CURRENCYCODE_ID
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART5"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART5")),
      right = (tbl("EDW_CML_DIM_SOURCE"), alias("EDW_CML_DIM_SOURCE")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART6"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.SOURCECODE_ID=EDW_CML_DIM_SOURCE.SOURCECODE_ID
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART6"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART6")),
      right = (tbl("ODS_TRANS_INMARKETSALES"), alias("ODS_TRANS_INMARKETSALES")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART7"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.PANELCODE_ID=EDW_CML_DIM_PANEL.PANEL_CD
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART7"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART7")),
      right = (tbl("EDW_CML_DIM_MARKET"), alias("EDW_CML_DIM_MARKET")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART8"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.MARKETCODE_ID=EDW_CML_DIM_MARKET.MARKETCODE_ID AND
 ODS_TRANS_INMARKETSALES.MOLECULENAME_ID=EDW_CML_DIM_MARKET.MOLECULENAME_ID
    """,
       how = 'LEFT'
    )



informatica_simple_join(
      left = (tbl("saswork.idwh_fct_inmarketsalesactuals2_CART8"), alias("saswork.idwh_fct_inmarketsalesactuals2_CART8")),
      right = (tbl("EDW_CML_DIM_SPECIALTY"), alias("EDW_CML_DIM_SPECIALTY")),
      target = tbl("saswork.idwh_fct_inmarketsalesactuals2_CART9"),
      truncate = True,
      onCondition ="""
        ODS_TRANS_INMARKETSALES.SPECIALTY_NM=EDW_CML_DIM_SPECIALTY.SPECIALTY_NM
    """,
       how = 'LEFT'
    )



selectCols = [
  (tbl("ODS_TRANS_INMARKETSALES"), col("MARKETCODEOPTPROD_SK")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PACKNAME_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTNAME_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("STRENGTHRATE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("MARKETCODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("SPECIALTY_NM")),
(tbl("ODS_TRANS_INMARKETSALES"), col("MARKETCODEOPTPROD_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("SOURCECODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("FINALDESTINATIONCOUNTRYCODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("MOLECULENAME_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("NFC123CODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("MANUFACTURERNAME_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("INTERNATIONALPRODUCTNAME_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("CORPORATIONNAME_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTATC3_CD")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTATC4_CD")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PANELCODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("MATERIALCODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTFAMILYCODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("LOCALCURRENCYCODE_ID")),
(tbl("ODS_TRANS_INMARKETSALES"), col("CONVERSIONLCTOEUR_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("CONVERSIONLCTOUSD_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWSALESINLC_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWSALESINEURO_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWSALESINDOLLAR_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWDOLLARREALMTHRT_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWEUROREALMTHRT_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWSALESINUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWSALESINSTDUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWSALESINCNTUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RXSPLIT_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINCNTUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINSTDUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINLC_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINEURO_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINDOLLAR_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINDOLLARREALMTHRT_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJSALESINEUROREALMTHRT_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("AVDOS_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("TREATDAYS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODTREATDAYS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODTREATDAYSONEMONTH_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODTREATDAYSTWOMONTHS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODTREATDAYSTHREEMONTHS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODTREATDAYSTOTAL_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODTOTALPATIENTSCURRMTH_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODTOTALPATIENTS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODPATIENTS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODFACTSALESINUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODADJUNITS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODNEWPATIENTS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODINDUCTIONPATIENTS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODCONTINUINGPATIENTS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATMODEXITPATIENTS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("MONTHSINCELAUNCH_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("SALESINMG")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PACKTYPE_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("COMPLIANCEPERSISTENCE_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RESTATEDDOSAGE_QTY")),
(tbl("ODS_TRANS_INMARKETSALES"), col("INDUCTIONDOSAGE_QTY")),
(tbl("ODS_TRANS_INMARKETSALES"), col("STARTINGDOSAGE_QTY")),
(tbl("ODS_TRANS_INMARKETSALES"), col("COMPLIANCE_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ESCALATION_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PERSTENCE_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWDISPPRESCNEW_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWDISPPRESCTOT_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWDISPPRESCCNTUNITSNEW_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("RAWDISPPRESCCNTUNITSTOT_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJDISPPRESCNEW_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJDISPPRESCTOT_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJDISPPRESCCNTUNITSNEW_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ADJDISPTOTALPRESCCNTUNITSTOT_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("EXCEPTION_FL")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTATC3ORIG_CD")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTATC4ORIG_CD")),
(tbl("ODS_TRANS_INMARKETSALES"), col("STRENGTHMG_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTBRANDGENERIC_FL")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCTSTRENGTHORIG_CD")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PRODUCT_CODE")),
(tbl("ODS_TRANS_INMARKETSALES"), col("PATIENTSHAREINPUT_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("EXITPATIENT_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("CUMUNIQUEPAT_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("SALESKG_AMT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPCOMPLIANCEFACTOR_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPSPLIT_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPVOLUMESPLIT_RT")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPAVDAYDOSAGE_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPTREATMENTDAYS_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPTREATMENTMONTH_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPSALESINMG_NBR")),
(tbl("ODS_TRANS_INMARKETSALES"), col("ETPCOUNT_NBR"))
]


expression = [
  """CASE
                WHEN ODS_TRANS_INMARKETSALES.MARKETCODE_ID IS NULL THEN - 1
                WHEN ODS_TRANS_INMARKETSALES.MARKETCODE_ID IS NOT NULL
                AND EDW_CML_DIM_MARKET.MARKET_SK IS NULL THEN - 2
                ELSE EDW_CML_DIM_MARKET.MARKET_SK
            END AS market_sk""",
"COALESCE(EDW_CML_DIM_SPECIALTY.SPECIALTY_SK, -2) AS specialty_sk",
"ODS_TRANS_INMARKETSALES.MONTH_ID AS month_sk",
"COALESCE(EDW_CML_DIM_PRODUCT.PRODUCT_SK, -2) AS product_sk",
"COALESCE(EDW_CML_DIM_PANEL.PANEL_SK, -2) AS panel_sk",
"ODS_TRANS_INMARKETSALES.LAUNCH_DT AS launchmonth_sk",
"COALESCE(EDW_CML_DIM_CURRENCY.CURRENCY_SK, -2) AS localcurrency_sk",
"COALESCE(EDW_CML_DIM_SOURCE.SOURCECODE_SK, -2) AS source_sk",
"COALESCE(EDW_CML_DIM_COUNTRY.COUNTRY_SK, -2) AS finaldestinationcountry_sk",
"COALESCE(EDW_DIM_PRODUCTFAMILY.PRODUCTFAMILY_SK, -3) AS productfamily_sk",
"COALESCE(EDW_CML_DIM_MATERIAL.MATERIAL_SK, -3) AS material_sk"
]



informatica_insertinto(
    source = (tbl("saswork.ods_trans_inmarketsales"), alias("ODS_TRANS_INMARKETSALES")),
    target = tbl("saswork.idwh_fct_inmarketsalesactuals2"),
    columns = selectCols,
expression = expression,
truncate = False,
distinct = False,

)
